<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Album example · Bootstrap</title>

    <link rel="stylesheet" href="<?php echo APP::config('url'); ?>public/css/bootstrap.css">
    <link rel="stylesheet" href="<?php echo APP::config('url'); ?>public/css/app.css">