
    <form class="form-signin" action="/index/authorization" method="post">
  <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
  <label for="email" class="sr-only">Email address</label>
  <input type="email" name="email" id="email" class="form-control" placeholder="Email address" required autofocus>
  <label for="pass" class="sr-only">Password</label>
  <input type="password" name="pass" id="pass" class="form-control" placeholder="Password" required>
  <div class="checkbox mb-3">
    <label>
      <input type="checkbox" value="remember-me"> Remember me
    </label>
  </div>
  <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
</form>
