<form action="/index/registernew" method="post">
  <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
  <label for="name" class="sr-only">User name</label>
  <input type="text" name="name" id="name" class="form-control" placeholder="User name" required autofocus>
  <label for="email" class="sr-only">Email address</label>
  <input type="email" name="email" id="email" class="form-control" placeholder="Email address" required autofocus>
  <label for="pass" class="sr-only">Password</label>
  <input type="password" name="pass" id="pass" class="form-control" placeholder="Password" required>
  <label for="passag" class="sr-only">Password</label>
  <input type="password" name="passag" id="passag" class="form-control" placeholder="Password again" required>
  </div>
  <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
</form>